// 雅思听力高频地标与设施词典 (Landmark & Facility Dictionary)
// 用于动态注入到方位训练、空间过渡及路线地图中
(() => {
  "use strict";

  const LANDMARKS = [
    { id: "library", term: "Library", phonetic: "/ˈlaɪbrəri/", chinese: "图书馆", category: "building", indoor: true },
    { id: "museum", term: "Museum", phonetic: "/mjuˈziːəm/", chinese: "博物馆", category: "building", indoor: true },
    { id: "community_hall", term: "Community Hall", phonetic: "/kəˈmjuːnəti hɔːl/", chinese: "社区大礼堂", category: "building", indoor: true },
    { id: "visitor_centre", term: "Visitor Centre", phonetic: "/ˈvɪzɪtə ˈsentə/", chinese: "游客服务中心", category: "facility", indoor: true },
    { id: "ticket_office", term: "Ticket Office", phonetic: "/ˈtɪkɪt ˈɒfɪs/", chinese: "售票处", category: "facility", indoor: true },
    { id: "car_park", term: "Car Park", phonetic: "/ˈkɑː pɑːk/", chinese: "停车场", category: "facility", indoor: false },
    { id: "lake", term: "Lake", phonetic: "/leɪk/", chinese: "人工湖 / 湖泊", category: "water", indoor: false },
    { id: "river", term: "River", phonetic: "/ˈrɪvə/", chinese: "河流 / 溪流", category: "water", indoor: false },
    { id: "bridge", term: "Bridge", phonetic: "/brɪdʒ/", chinese: "桥梁 / 木桥", category: "traffic", indoor: false },
    { id: "trees", term: "Pine Trees", phonetic: "/paɪn triːz/", chinese: "松树林 / 树林", category: "nature", indoor: false },
    { id: "playground", term: "Playground", phonetic: "/ˈpleɪɡraʊnd/", chinese: "儿童游乐场", category: "facility", indoor: false },
    { id: "factory", term: "Factory", phonetic: "/ˈfæktri/", chinese: "工厂厂房", category: "building", indoor: true },
    { id: "warehouse", term: "Warehouse", phonetic: "/ˈweəhaʊs/", chinese: "仓储库房", category: "building", indoor: true },
    { id: "barn", term: "Barn", phonetic: "/bɑːn/", chinese: "大谷仓", category: "building", indoor: true },
    { id: "orchard", term: "Orchard", phonetic: "/ˈɔːtʃəd/", chinese: "果园", category: "nature", indoor: false },
    { id: "garden", term: "Rose Garden", phonetic: "/rəʊz ˈɡɑːdn/", chinese: "玫瑰花园", category: "nature", indoor: false },
    { id: "pond", term: "Pond", phonetic: "/pɒnd/", chinese: "池塘 / 水塘", category: "water", indoor: false },
    { id: "reception", term: "Reception", phonetic: "/rɪˈsepʃn/", chinese: "接待处 / 前台大厅", category: "building", indoor: true },
    { id: "cloakroom", term: "Cloakroom", phonetic: "/ˈkləʊkrʊm/", chinese: "衣帽寄存间", category: "facility", indoor: true },
    { id: "exhibition_hall", term: "Exhibition Hall", phonetic: "/ˌeksɪˈbɪʃn hɔːl/", chinese: "主展览大厅", category: "building", indoor: true },
    { id: "education_centre", term: "Education Centre", phonetic: "/ˌedʒuˈkeɪʃn ˈsentə/", chinese: "教育研习中心", category: "building", indoor: true },
    { id: "cafe", term: "Café", phonetic: "/ˈkæfeɪ/", chinese: "咖啡馆 / 茶座", category: "facility", indoor: true },
    { id: "shop", term: "Gift Shop", phonetic: "/ɡɪft ʃɒp/", chinese: "礼品商店", category: "facility", indoor: true },
    { id: "entrance", term: "Main Entrance", phonetic: "/meɪn ˈentrəns/", chinese: "主出入口", category: "access", indoor: false },
    { id: "gate", term: "South Gate", phonetic: "/saʊθ ɡeɪt/", chinese: "南门 / 入口铁门", category: "access", indoor: false },
    { id: "railway", term: "Railway Track", phonetic: "/ˈreɪlweɪ træk/", chinese: "铁轨 / 铁路线", category: "traffic", indoor: false },
    { id: "platform", term: "Platform", phonetic: "/ˈplætfɔːm/", chinese: "月台 / 乘车平台", category: "traffic", indoor: false },
    { id: "sports_field", term: "Sports Field", phonetic: "/spɔːts fiːld/", chinese: "户外运动场 / 草坪运动区", category: "facility", indoor: false },
    { id: "fountain", term: "Central Fountain", phonetic: "/ˈfəʊntɪn/", chinese: "中央喷泉", category: "nature", indoor: false },
    { id: "greenhouse", term: "Greenhouse", phonetic: "/ˈɡriːnhaʊs/", chinese: "温室花房", category: "building", indoor: true },
    { id: "maze", term: "Hedge Maze", phonetic: "/hedʒ meɪz/", chinese: "树篱迷宫", category: "nature", indoor: false },
    { id: "smithy", term: "Smithy", phonetic: "/ˈsmɪði/", chinese: "铁匠铺 / 锻造房", category: "building", indoor: true },
    { id: "stables", term: "Horse Stables", phonetic: "/hɔːs ˈsteɪblz/", chinese: "马厩", category: "building", indoor: true },
    { id: "campsite", term: "Campsite", phonetic: "/ˈkæmpsaɪt/", chinese: "露营帐篷营地", category: "facility", indoor: false },
    { id: "pavilion", term: "Band Pavilion", phonetic: "/pəˈvɪljən/", chinese: "凉亭 / 露天乐坛", category: "facility", indoor: false },
    { id: "footbridge", term: "Footbridge", phonetic: "/ˈfʊtbrɪdʒ/", chinese: "步行桥 / 观景木人行桥", category: "traffic", indoor: false }
  ,
    {"id":"aviary","term":"Bird Aviary","phonetic":"/ˈeɪviəri/","chinese":"大型观鸟鸟舍","category":"facility","indoor":true},
    {"id":"boathouse","term":"Boathouse","phonetic":"/ˈbəʊthaʊs/","chinese":"游艇码头船库","category":"water","indoor":true},
    {"id":"picnic_shelter","term":"Picnic Shelter","phonetic":"/ˈpɪknɪk ˈʃeltə/","chinese":"遮阳野餐凉亭","category":"facility","indoor":false},
    {"id":"viewing_platform","term":"Viewing Platform","phonetic":"/ˈvjuːɪŋ ˈplætfɔːm/","chinese":"高架观景展望台","category":"facility","indoor":false},
    {"id":"windmill","term":"Historic Windmill","phonetic":"/hɪˈstɒrɪk ˈwɪndmɪl/","chinese":"历史风车磨坊","category":"building","indoor":true},
    {"id":"watermill","term":"Old Watermill","phonetic":"/əʊld ˈwɔːtəmɪl/","chinese":"水力磨坊木屋","category":"building","indoor":true},
    {"id":"herb_garden","term":"Medicinal Herb Garden","phonetic":"/mɪˈdɪsnl hɜːb ˈɡɑːdn/","chinese":"药用草本植物园","category":"nature","indoor":false},
    {"id":"courtyard","term":"Central Courtyard","phonetic":"/ˈsentrəl ˈkɔːtjɑːd/","chinese":"建筑中央内庭院","category":"facility","indoor":false},
    {"id":"atrium","term":"Glass Atrium","phonetic":"/ɡlɑːs ˈeɪtriəm/","chinese":"采光玻璃中庭大厅","category":"building","indoor":true},
    {"id":"lecture_theatre","term":"Main Lecture Theatre","phonetic":"/meɪn ˈlektʃə ˈθɪətə/","chinese":"主阶梯大讲堂","category":"building","indoor":true},
    {"id":"seminar_room","term":"Seminar Room","phonetic":"/ˈsemɪnɑː rʊm/","chinese":"研讨辅导教室","category":"building","indoor":true},
    {"id":"pottery_workshop","term":"Pottery Studio","phonetic":"/ˈpɒtəri ˈstjuːdiəʊ/","chinese":"陶艺手工作坊","category":"building","indoor":true},
    {"id":"bicycle_shed","term":"Covered Bicycle Shed","phonetic":"/ˈkʌvəd ˈbaɪsɪkl ʃed/","chinese":"带棚自行车存放处","category":"facility","indoor":false},
    {"id":"conservatory","term":"Tropical Conservatory","phonetic":"/ˈtrɒpɪkl kənˈsɜːvətri/","chinese":"热带植物保温暖房","category":"building","indoor":true},
    {"id":"aquarium","term":"Marine Aquarium","phonetic":"/məˈriːn əˈkweəriəm/","chinese":"海洋生物水族馆","category":"building","indoor":true},
    {"id":"observatory","term":"Astronomical Observatory","phonetic":"/ˌæstrəˈnɒmɪkl əbˈzɜːvətri/","chinese":"圆顶天文观测台","category":"building","indoor":true},
    {"id":"statue","term":"Bronze Founder's Statue","phonetic":"/brɒnz ˈfaʊndəz ˈstætʃuː/","chinese":"先驱者青铜纪念像","category":"nature","indoor":false},
    {"id":"amphitheatre","term":"Open-Air Amphitheatre","phonetic":"/ˌəʊpən ˈeər ˈæmfɪθɪətə/","chinese":"露天半圆阶梯剧场","category":"facility","indoor":false},
    {"id":"clock_tower","term":"Central Clock Tower","phonetic":"/ˈsentrəl klɒk ˈtaʊə/","chinese":"园区中央大钟楼","category":"building","indoor":true},
    {"id":"first_aid","term":"First Aid Station","phonetic":"/fɜːst eɪd ˈsteɪʃn/","chinese":"红十字急救医务站","category":"facility","indoor":true},
    {"id":"information_kiosk","term":"Information Kiosk","phonetic":"/ˌɪnfəˈmeɪʃn ˈkiːɒsk/","chinese":"电子触摸问询服务亭","category":"facility","indoor":false},
    {"id":"wildflower_meadow","term":"Wildflower Meadow","phonetic":"/ˈwaɪldflaʊə ˈmedəʊ/","chinese":"野花生态保育草甸","category":"nature","indoor":false},
    {"id":"bee_hives","term":"Apiary Bee Hives","phonetic":"/ˈeɪpiəri biː haɪvz/","chinese":"养蜂科普蜂箱区","category":"nature","indoor":false},
    {"id":"sculpture_walk","term":"Sculpture Promenade","phonetic":"/ˈskʌlptʃə ˌprɒməˈnɑːd/","chinese":"当代艺术雕塑林荫道","category":"nature","indoor":false}
  ];

  window.MAP_LANDMARKS_DATA = LANDMARKS;
})();
